name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@335648fbc85ddf08e2d79fb5def7642e77936dec
        with:
          labels: |
            stale
            waiting-reply
