name: Automate labeled issues
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project-url: "https://github.com/orgs/hashicorp/projects/59"
        column-name: "Blocked"
        label-name: "waiting-response"
